name: CD | Test End-to-End

on:
  push:
    branches-ignore:
      - "refs/tags/*"

jobs:
  mati_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Extract version from the pull request description
            pull_request_description="${{ github.event.pull_request.body }}"
            version=$(echo "$pull_request_description" | grep -oP 'Version: \K[0-9.]+')

            if [ -z "$version" ]; then
              # If no version found, use a default
              version="1.0"
            fi

            echo "DOCKER_TAG=latest:${version}" >> $GITHUB_ENV
            echo "${version}" >> $GITHUB_ENV
          else
            branch_name=$(echo "${{ github.ref }}" | awk -F/ '{print $3}')
            echo "DOCKER_TAG=dev_v${branch_name}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ env.DOCKER_TAG }}