name: CD | Test End-to-End

on:
  push:
    branches-ignore:
      - "refs/tags/*"

jobs:
  mati_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            current_version=${{ vars.RELEASE_VERSION }}
            # Use node.js for floating-point arithmetic
            new_version=$(node -e "console.log((${current_version} + 0.01).toFixed(2))")
            echo "DOCKER_TAG=latest:${new_version}" >> $GITHUB_ENV
            echo "${new_version}" >> $GITHUB_ENV
          else
            branch_name=$(echo "${{ github.ref }}" | awk -F/ '{print $3}')
            echo "DOCKER_TAG=dev_v${branch_name}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ env.DOCKER_TAG }}